### ISSUE TITLE
Microsoft To-Do incorrect "today" label

### ISSUE THREAD

**Issue by Bibbleq** [dakboard/Cloud-Platform#13]
I've built a screen with an integration to Microsoft To-Do & it's pulling tasks through just fine however the due date is 1 day out.

I have some tasks that are due tomorrow but the label shown in Dakboard is "today". Where the due date is for in the future i.e. Sept 24th this is shown just fine. I've confirmed the dates & settings are fine in MS To-Do itself.

Having raised a support ticket I've been told to post here instead...

**Comment by cocarrig** [comment]
Hi,

If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.
