### ISSUE TITLE
Bug: Reddit photos not chosing new photos

### ISSUE THREAD

**Issue by itsJulike** [dakboard/Cloud-Platform#15]
When I choose my own subreddit r/Julike it only chooses one image, and doesn't switch between images.
If I choose other subreddits (like r/funny or r/aww) it works fine. 

I have no idea of how to fix this. 
I've tried removing, and readding the block several times, but to no help.

**Comment by cocarrig** [comment]
Hi,

I was able to test this and was unable to recreate the issue you are describing.  If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.
