### ISSUE TITLE
Family planner wall

### ISSUE THREAD

**Issue by foging** [dakboard/Cloud-Platform#17]
It would be really useful for me and my family if you could add an option to view several calendars in a monthly and weekly view, where each calendar is in the columns and the dates in the rows. Similar to the linked image.

![image](https://cloud.githubusercontent.com/assets/23657696/20525174/7ba0e240-b0be-11e6-8c03-8310018abe3f.png)

[http://www.free-reward-cards.com/uploads/kaart/kaart/familieplanner2_engels.jpg](url)

**Comment by cocarrig** [comment]
Hi,

This can be performed by creating separate agenda style calendar blocks for each calendar showing all days regardless of appointment, and custom formatting options. Additional text blocks can be added for more personalization as well.

If you have any comments or concerns please reach out to us at support@dakboard.com.
