### ISSUE TITLE
Separation (grouping) of calendars in agenda mode

### ISSUE THREAD

**Issue by Flytrapp** [dakboard/Cloud-Platform#18]
Great project! 

I would love the ability to add groups/separators to the calendar when using agenda view. 
So that 2 or more people can share one calendar without the clutter of having everything on top of eachother. Basicly adding 1-2 cm of space between the groups to easily separate the agendas.
Maybe even adding a name option on the side?

Might be as easy UI vise to add a "group" options and having the option to decide what group goes first.

Wrote you an email about this but I can't see it here yet so I thought I would make the post for you and add another illustration of what I imagine. 
![calendar](https://cloud.githubusercontent.com/assets/24585025/21218923/e3135b14-c2b2-11e6-814a-aadb73b5ff32.png)

**Comment by cocarrig** [comment]
Hi,

This can be performed by creating separate agenda style calendar blocks for each calendar showing all days regardless of appointment, and custom formatting options.  Additional text blocks can be added for more personalization as well.

If you have any comments or concerns please reach out to us at support@dakboard.com.
