### ISSUE TITLE
RFE Wheather units

### ISSUE THREAD

**Issue by Uttiponken** [dakboard/Cloud-Platform#24]
I'd like to ask for another weather unit setting in addition to the Imperial and Metric version provided. 
The reason is because "most" countries (US obviously excepted), measure heat in degrees Celsius and wind speed in meters/second rather than km/h. Would it be possible to add unit choice "Metric (Celcius/meters)"?

**Comment by cocarrig** [comment]
Unfortunately due to lack of interest and a high level of effort to implement we are not pursuing this enhancement at this time.

If you have any questions or concerns please reach out to support@dakboard.com.
