### ISSUE TITLE
MQTT display

### ISSUE THREAD

**Issue by marksev1** [dakboard/Cloud-Platform#25]
Please add support for displaying data sent with the very popular MQTT protocol used for home automation. (I think this should be a mqtt client scenario). There are many apps on the Play Store that support MQTT.

**Comment by cocarrig** [comment]
Unfortunately after review this integration poses a few challenges, this is not necessarily the direction that DAKboard is looking to pursue with its level of functionality.  We continue to anticipate support for Samsung Smartthings and are pursuing other smart home available cloud options.

If you have any comments of concerns please reach out to support@dakboard.com.
