### ISSUE TITLE
Enhancement: Support for Amazon Fire TV

### ISSUE THREAD

**Issue by mpwalters** [dakboard/Cloud-Platform#27]
The DAKBoard app is available within the Amazon App Store (https://www.amazon.com/dp/B06VSWM8YZ/). While useful on a tablet, it isn't offered through Amazon as being supported on a Fire TV.
  
I have just "purchased" the app through Amazon and will try it anyway, presuming Amazon's synching and downloading from the Fire TV will permit me.  I know could try sideloading or downloading an APK, but the idea for this enhancement is to have direct support from within the Amazon app store infrastructure.

**Comment by cocarrig** [comment]
Unfortunately we have reviewed this request and made a determination not to move forward due to insufficient customer interest.

If you have any comments or concerns please reach out to us at support@dakboard.com.
