### ISSUE TITLE
Breaking News Alert

### ISSUE THREAD

**Issue by himynamesned** [dakboard/Cloud-Platform#28]
Similar to the weather alerts banner, if a particular RSS feed has a new item (within a particular time frame maybe) the feed item is highlighted either at the top of the display or within the RSS section.

**Comment by cocarrig** [comment]
Unfortunately we have reviewed this request and made a determination not to move forward due to insufficient customer interest.

We recommend using a timestamp to indicate when the feed was published.

If you have any comments or concerns please reach out to us at support@dakboard.com.
