### ISSUE TITLE
Read photo metadata

### ISSUE THREAD

**Issue by markjessell** [dakboard/Cloud-Platform#30]
Hi it would be great if DAKBoard could use photo metadata stored with the images for filling the titles (since Dropbox doesn't have a separate metadata system).

Thanks.

**Comment by cocarrig** [comment]
For select photo sources (I.E. Dopbox, Google Drive, Flickr, Google Photos, etc) we do pull metadata where available at this time.

 If you have any comments or concerns please reach out to us at support@dakboard.com.
