### ISSUE TITLE
Add Google Assistant Amazon Alexa

### ISSUE THREAD

**Issue by jmiele4** [dakboard/Cloud-Platform#31]
This may be possible through user programming but would be great to have in the official build. Can you add Google Assistant or Amazon Alexa to the Raspberry Pi software? 

I was thinking this may even be possible with your existing hardware as the DAKboard CPU looks to already be based of a Raspberry Pi and has USB ports for a microphone, camera and speakers.

**Comment by cocarrig** [comment]
We have some requests open that indicate specific functionality that our clients would like displayed on DAKboard.  If you have an idea of specific functionality please comment on those requests or feel free to detail a new request with your desired features.

If you have any comments or concerns please reach out to us at support@dakboard.com.
