### ISSUE TITLE
Chromecast/UPnP Support

### ISSUE THREAD

**Issue by denzuko** [dakboard/Cloud-Platform#32]
Considering that DAKBoard is a web application it would not be to difficult to add in support for google's DIAL protocol and UPnP discovery. A right up on how this is done without needing extra sdk's is availalbe at https://github.com/jloutsenhizer/CR-Cast/wiki/Chromecast-Implementation-Documentation-WIP.

Use Case:

DAKboard registers with network then detects additional Chromecast devices. Via control panel and/or android app user then can "extend" the display into the chromecast and/or use chromecast as a additional display.

**Comment by cocarrig** [comment]
Unfortunately we have reviewed this request and made a determination not to move forward due alternative methods detailed within this request that are available to extend DAKboard to additional devices specified.

If you have any comments or concerns please reach out to us at support@dakboard.com.
