### ISSUE TITLE
Alignment Issues

### ISSUE THREAD

**Issue by himynamesned** [dakboard/Cloud-Platform#34]
![2018-03-28-134230_1080x1920_scrot](https://user-images.githubusercontent.com/25020297/38029761-aaee5728-328e-11e8-8be2-093778de962e.png)

Please allow finer adjustments in both vertical and horizontal adjustments. As you can see above, this is the best I can get when aligning the Nest to the weather and just looks out of place.

**Comment by cocarrig** [comment]
Hi,

If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.
