### ISSUE TITLE
Financial block not update after schedule display

### ISSUE THREAD

**Issue by wallylee99** [dakboard/Cloud-Platform#5]
I have 10 symbols and enabled it to scroll across screen. It is also scheduled for display from 8pm to 1am daily.

I found that the block will stop scrolling after it was hidden and reappeared on the next day.

**Comment by cocarrig** [comment]
Hi,

If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.
