### ISSUE TITLE
Reoccurring Google Calendar Events showing on incorrect day

### ISSUE THREAD

**Issue by SSNDemon** [dakboard/Cloud-Platform#6]
Continuation of bug from https://github.com/dakboard/feature-requests/issues/31

**Comment by cocarrig** [comment]
Hi,

DAKboard recommends the use of authenticated calendar options were possible (I.E. google and microsoft) which have been deployed for increased security and addresses this issues with reoccurring events.

If you are still experiencing this issue on DAKboard please reach out to support@dakboard.com.  A member of support team can gather additional detail and compose a bug issue or help to identify a configuration issue by working with you on your account.

**Comment by himynamesned** [comment]
@cocarrig after complaining about these issues since 2018 you close them without invest and palm us off to some customer service team. Awful
